#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# loop init — guided setup. Points the kernel at YOUR project, with YOUR goal and
# YOUR objective check. Writes a small .loop/ folder into the target project and
# prints both ways to drive it: the autonomous runner, and a ready-to-paste /goal.
#
# Non-interactive use (CI, scripting): pre-set any answer as an env var, e.g.
#   PROJECT_DIR=. GOAL="..." CHECK_CMD="npm test" ./init.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
INSTALL_DIR="$(cd "$(dirname "$0")" && pwd)"

ask() { # ask VAR "question" "default"
  local var="$1" q="$2" def="${3:-}" cur ans
  eval "cur=\${$var:-}"
  if [ -n "$cur" ]; then return; fi            # already provided via env
  if [ -t 0 ]; then
    if [ -n "$def" ]; then printf "  %s [%s]: " "$q" "$def"; else printf "  %s: " "$q"; fi
    read -r ans || ans=""
  else
    ans=""
  fi
  [ -z "$ans" ] && ans="$def"
  eval "$var=\$ans"
}

echo "┌─ loop init ───────────────────────────────────────────────"
echo "│ Answer a few questions. Nothing runs until you say so."
echo "└───────────────────────────────────────────────────────────"
ask PROJECT_DIR "Project directory to build in" "$(pwd)"
ask GOAL        "One-line goal (what should the loop make true?)" ""
ask CHECK_CMD   "Check command that defines DONE (exit 0 = done)" "npm test"
ask MAX_ITERS   "Max iterations (hard cap)" "20"
ask NOPROGRESS_K "Stop after N no-progress iterations" "4"

if [ -z "${GOAL:-}" ]; then
  echo "✗ A goal is required. Re-run and describe what to build." >&2
  exit 1
fi

PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
LOOP_DIR="$PROJECT_DIR/.loop"
mkdir -p "$LOOP_DIR"

# 1) The worker's brief (its memory-allocation, re-read every iteration)
cat > "$LOOP_DIR/GOAL.md" <<EOF
# Goal
$GOAL

You are ONE iteration of an autonomous loop building this project. The loop scores your
work by running this command and reading its exit code — you cannot fake it:

    $CHECK_CMD        # exit 0 means DONE

## Discipline (one thing per iteration)
- CONSULT the LEDGER appended below before acting; never repeat an approach that already failed.
- Make the smallest change that should move the check toward passing, then STOP and let the
  loop re-score.
- Do NOT weaken, skip, or delete checks/tests to make the command pass. That is the failure,
  not the fix — and the kernel re-runs the real command anyway.

## Memory
If something failed, append one line: FAIL (what) -> INVESTIGATE (why) -> VERIFY (checked fact)
-> DISTILL (the rule) so the next iteration learns.
EOF

# 2) The objective scorer: run the user's check, map exit code -> score
cat > "$LOOP_DIR/score.sh" <<EOF
#!/usr/bin/env bash
# Auto-generated by loop init. Objective check for: $GOAL
set -uo pipefail
cd "$PROJECT_DIR"
if $CHECK_CMD >/dev/null 2>&1; then
  echo "score=1.0000"; exit 0
else
  echo "score=0.0000"; exit 1
fi
EOF
chmod +x "$LOOP_DIR/score.sh"

# 3) The run config the `loop` wrapper sources
cat > "$LOOP_DIR/loop.env" <<EOF
# Auto-generated by loop init on $(date +%Y-%m-%d)
TASK_DIR="$PROJECT_DIR"
SCORER="$LOOP_DIR/score.sh"
PROMPT_FILE="$LOOP_DIR/GOAL.md"
MAX_ITERS=$MAX_ITERS
NOPROGRESS_K=$NOPROGRESS_K
EOF

# 4) A ready-to-paste /goal for people working INSIDE Claude Code
cat > "$LOOP_DIR/goal.txt" <<EOF
/goal $GOAL Done when \`$CHECK_CMD\` exits 0. Check: paste the command's output in the
conversation. Constraints: do not modify, skip, or delete tests/assertions to pass; keep the
diff minimal; if a check must legitimately change, STOP and report instead. Or stop after
$MAX_ITERS turns.
EOF

echo
echo "✓ Configured  $LOOP_DIR"
echo "    GOAL.md   the worker's brief"
echo "    score.sh  objective check  ($CHECK_CMD)"
echo "    loop.env  caps: max=$MAX_ITERS  no-progress=$NOPROGRESS_K"
echo
echo "▶ Run it autonomously (walk away):"
echo "    $INSTALL_DIR/loop run \"$PROJECT_DIR\""
echo
echo "▶ Or paste this into Claude Code:"
echo "    ─────────────────────────────────────────────────────────"
sed 's/^/    /' "$LOOP_DIR/goal.txt"
echo "    ─────────────────────────────────────────────────────────"
